[package]
name = "darkkit"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.13", features = ["audio", "backtrace", "glam-serde", "log-rs"] }

[[example]]
name = "windows"

